### ISSUE TITLE
[devMode] Transform styles to developer-friendly classNames

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-look#173]
Converting styles into developer-friendly namespaced (local scoped) classes could be much more easier to debug.
e.g.

```javacscript
const styles = StyleSheet.create(Component, {
  box: {
     fontSize: 13,
     color: 'red'
  },
  container: {
    backgroundColor: 'blue'
  }
})
```

could be transformed to:
```CSS
.Component .box {
   font-size: 13px;
   color: red;
}

.Component .container {
   background-color: blue
}
```
