### ISSUE TITLE
Supported media queries nested under `@media screen` and `@media only screen`

### ISSUE THREAD

**Issue by hallister** [rofrischmann/react-look#277]
**Version**: 1.0.0 (beta5)
**Environment**: React
**Type**: Bug

-------------------
#### Description
`@media only screen` and `@media screen` queries result in child media queries not working. When nesting a media query below `@media screen`, the nested media queries don't exist.

#### Steps to reproduce
1. First step
2. Second step

#### Expected Behavior
```javascript
{
  '@media only screen': {
    '@media (min-width: 1281px)': {
      maxWidth: '1200px'
    },
    '@media (min-width: 1024px)': {
      maxWidth: '1100px'
    }
  }
}
```

```css
@media only screen and (min-width: 1281px) {
  max-width: 1200px
}

@media only screen and (min-width: 1281px) {
  max-width: 1100px
}

```

#### Actual Behavior
*No CSS is generated*

#### Proposal
Any information on how this might be achieved.

**Code Example**:
```javascript
// your proposal here
```
