### ISSUE TITLE
StyleSheet.addCSS() failing for multi-token declarations

### ISSUE THREAD

**Issue by jordanh** [rofrischmann/react-look#289]
**Version**: 1.0.0 (beta9)
**Environment**: React
**Type**: Bug

-------------------
#### Description

CSS like the below (taken from `StyleContainer-test.js`)...

```css
/*!
 *  Banner
 */
.h1 {
  color: red;
  margin: 10px 10px 10px 10px;
}
```

...will be mangled by the current implementation within `StyleContainer.js`.

#### Expected Behavior
It should result in something like:

```css
/*!*Banner*/.h1 {color: red;margin: 10px 10px 10px 10px;}'
```

#### Actual Behavior
The regex replace on `StyleContainer.js:66` is given as `styles.replace(/\s+/g, '')` which will mangle the above `margin:` declaration to:

```
margin:10px10px10px10px;
```

Which is _no bueno!_
