### ISSUE TITLE
Optimization is breaking overrides

### ISSUE THREAD

**Issue by ericmuyser** [rofrischmann/react-look#292]
**Version**: 1.0.0 (beta9)
**Environment**: React
**Type**: Bug

-------------------
#### Description

Hey man, there's a problem where the declarations being sent to react-look are not being output in the right order in the `<style>` tag. The reason looks to be due to an optimization where it reuses doesn't output new declarations if they have the same properties. But that's not an optimization that can logically work all the time, because if there's other declarations between those 2 points, it's important they retain position, to override.

I verified before sending to `react-look`, the declarations are in the right order in the object:

![image](https://cloud.githubusercontent.com/assets/156768/16106638/1c6ef92e-334b-11e6-83f7-5bc4a3f5db3d.png)

And then after output inside the `<style>`:

![image](https://cloud.githubusercontent.com/assets/156768/16106650/3196f086-334b-11e6-8f40-869958c958eb.png)

The result is it's overriding the wrong color:

![image](https://cloud.githubusercontent.com/assets/156768/16106675/458548ae-334b-11e6-8930-e113fa516337.png)

#### Steps to reproduce

Create declarations that have the same attributes but one before and one after, shown above.

#### Expected Behavior
```css
.c-timeline__item {
    /* stuff here */
}

.c-timeline__item.c--red {
    background: #D12313;
}

.c-timeline__item.c--orange {
    background: #E66924;
}

.c-timeline__item.c--yellow {
    background: #DEBD3D;
}

.c-timeline__item.c--yellow {
    background: #DEBD3D;
}

.c-timeline__item.c--green {
    background: #008835;
}

.c-timeline__item.c--blue {
    background: #0066BC;
}


.c-timeline__arrow {
    background: grey;
    /* stuff here */
}

.c-timeline__arrow.c--completed {
    opacity: 1;
}

.c-timeline__arrow.c--red {
    background: #D12313;
}

.c-timeline__arrow.c--orange {
    background: #E66924;
}

.c-timeline__arrow.c--yellow {
    background: #DEBD3D;
}

.c-timeline__arrow.c--green {
    background: #008835;
}

.c-timeline__arrow.c--blue {
    background: #0066BC;
}
```

`.c-timeline__arrow.c--blue` should result in `background: #0066BC`

#### Actual Behavior

`.c-timeline__arrow.c--blue` actually results in `background: grey`

#### Proposal

When generating the `<style>` tag, the declarations should be in the right order
